"""Pinned column validation contract; no runtime dependency on repository docs."""

KEY_FIELDS = {
    "archive_manifest": [
        "artifact_manifest_id",
        "verification_state",
        "preservation_report_id",
        "restore_report_id",
    ],
    "artifact_manifest": ["manifest_kind", "content_hash"],
    "book_level": ["snapshot_id", "side", "level"],
    "book_snapshot": ["source_observation_id", "token_outcome_id", "reconstruction_version"],
    "condition_identity": ["chain_id", "condition_id", "mapping_version"],
    "event_group_membership": [
        "group_version",
        "event_group_id",
        "member_identity_id",
        "relationship_type",
        "mapping_view",
    ],
    "experiment_run": [
        "experiment_id",
        "protocol_version",
        "candidate_manifest_id",
        "stage",
        "result_manifest_id",
    ],
    "feature_definition": ["feature_id", "feature_version"],
    "feature_value": ["origin_id", "feature_definition_id", "transform_version"],
    "information_event_version": [
        "document_id",
        "text_hash",
        "extraction_model_version",
        "prompt_hash",
        "matching_version",
    ],
    "label_version": [
        "origin_id",
        "target_definition_id",
        "label_computation_version",
        "outcome_observation_ids",
        "supersedes_label_id",
    ],
    "market_identity_version": ["venue", "market_id", "mapping_version", "observed_from_at"],
    "outcome_observation": ["origin_id", "target_definition_id", "source_observation_id"],
    "prediction": [
        "origin_id",
        "experiment_run_id",
        "model_version",
        "target_definition_id",
        "calibration_version",
    ],
    "research_origin": [
        "sampling_manifest_id",
        "token_outcome_id",
        "scheduled_origin_at",
        "trigger_id",
        "prediction_origin_at",
    ],
    "source_observation": ["source_registry_id", "request_id", "receipt_ordinal"],
    "source_registry": ["source_id", "registry_version"],
    "target_definition": ["target_version"],
    "token_outcome_version": ["market_identity_id", "token_id", "outcome_index", "mapping_version"],
    "trade_observation": ["source_observation_id", "trade_id", "deduplication_version"],
    "wallet_state_version": [
        "chain_id",
        "wallet_id",
        "token_outcome_id",
        "as_of_cutoff_at",
        "state_definition_version",
        "history_manifest_id",
    ],
}

FIELD_SPECS = {
    "archive_manifest": {
        "artifact_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "byte_count": {"nullable": "false", "reference": "", "type": "INT64"},
        "file_hashes": {"nullable": "false", "reference": "", "type": "JSON"},
        "format_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "partition_bounds": {"nullable": "false", "reference": "", "type": "JSON"},
        "preservation_report_id": {
            "nullable": "true",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "restore_report_id": {
            "nullable": "true",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "row_count": {"nullable": "false", "reference": "", "type": "INT64"},
        "schema_hash": {"nullable": "false", "reference": "", "type": "HASH"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "source_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "supersedes_id": {"nullable": "true", "reference": "archive_manifest.id", "type": "HASH"},
        "verification_state": {"nullable": "false", "reference": "", "type": "ENUM"},
    },
    "artifact_manifest": {
        "available_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "content_hash": {"nullable": "false", "reference": "", "type": "HASH"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "manifest_kind": {"nullable": "false", "reference": "", "type": "ENUM"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "object_hash": {"nullable": "true", "reference": "", "type": "HASH"},
        "object_uri": {"nullable": "true", "reference": "", "type": "TEXT"},
        "payload": {"nullable": "false", "reference": "", "type": "JSON"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
    },
    "book_level": {
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "level": {"nullable": "false", "reference": "", "type": "INT64"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "price_decimal": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "price_raw": {"nullable": "false", "reference": "", "type": "TEXT"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "side": {"nullable": "false", "reference": "", "type": "ENUM"},
        "size_decimal": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "size_raw": {"nullable": "false", "reference": "", "type": "TEXT"},
        "snapshot_id": {"nullable": "false", "reference": "book_snapshot.id", "type": "TEXT"},
        "source_observation_id": {
            "nullable": "false",
            "reference": "source_observation.id",
            "type": "HASH",
        },
        "unit": {"nullable": "false", "reference": "", "type": "TEXT"},
    },
    "book_snapshot": {
        "ask_level_count": {"nullable": "false", "reference": "", "type": "INT64"},
        "ask_state": {"nullable": "false", "reference": "", "type": "ENUM"},
        "available_to_model_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "bid_level_count": {"nullable": "false", "reference": "", "type": "INT64"},
        "bid_state": {"nullable": "false", "reference": "", "type": "ENUM"},
        "book_hash": {"nullable": "true", "reference": "", "type": "TEXT"},
        "delta_observation_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "previous_snapshot_id": {
            "nullable": "true",
            "reference": "book_snapshot.id",
            "type": "HASH",
        },
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "quote_age_ms": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "quote_age_semantics": {"nullable": "false", "reference": "", "type": "ENUM"},
        "reconstruction_status": {"nullable": "false", "reference": "", "type": "ENUM"},
        "reconstruction_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "sequence_end": {"nullable": "true", "reference": "", "type": "TEXT"},
        "sequence_start": {"nullable": "true", "reference": "", "type": "TEXT"},
        "snapshot_kind": {"nullable": "false", "reference": "", "type": "ENUM"},
        "source_observation_id": {
            "nullable": "false",
            "reference": "source_observation.id",
            "type": "HASH",
        },
        "token_outcome_id": {
            "nullable": "false",
            "reference": "token_outcome_version.id",
            "type": "HASH",
        },
    },
    "condition_identity": {
        "chain_id": {"nullable": "true", "reference": "", "type": "INT64"},
        "collateral_address": {"nullable": "true", "reference": "", "type": "ADDRESS"},
        "collateral_decimals": {"nullable": "true", "reference": "", "type": "INT64"},
        "condition_id": {"nullable": "true", "reference": "", "type": "HEX32"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "identity_status": {"nullable": "false", "reference": "", "type": "ENUM"},
        "mapping_evidence_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "mapping_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "observed_from_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "question_id": {"nullable": "true", "reference": "", "type": "HEX32"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "supersedes_id": {"nullable": "true", "reference": "condition_identity.id", "type": "HASH"},
        "venue": {"nullable": "false", "reference": "", "type": "TEXT"},
    },
    "event_group_membership": {
        "event_group_id": {"nullable": "true", "reference": "", "type": "TEXT"},
        "group_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "mapping_confidence": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "mapping_evidence_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "mapping_method": {"nullable": "false", "reference": "", "type": "TEXT"},
        "mapping_view": {"nullable": "false", "reference": "", "type": "ENUM"},
        "member_identity_id": {
            "nullable": "false",
            "reference": "market_identity_version.id",
            "type": "HASH",
        },
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "observed_from_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "relationship_type": {"nullable": "false", "reference": "", "type": "ENUM"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "supersedes_id": {
            "nullable": "true",
            "reference": "event_group_membership.id",
            "type": "HASH",
        },
        "valid_from_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "valid_to_at": {"nullable": "true", "reference": "", "type": "UTC"},
    },
    "experiment_run": {
        "candidate_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "experiment_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "protocol_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "protocol_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "registered_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "result_manifest_id": {
            "nullable": "true",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "split_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "stage": {"nullable": "false", "reference": "", "type": "ENUM"},
        "supersedes_id": {"nullable": "true", "reference": "experiment_run.id", "type": "HASH"},
        "verdict": {"nullable": "false", "reference": "", "type": "ENUM"},
    },
    "feature_definition": {
        "feature_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "feature_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "formula": {"nullable": "false", "reference": "", "type": "TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "minimum_coverage": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "missingness_policy": {"nullable": "false", "reference": "", "type": "JSON"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "raw_dependencies": {"nullable": "false", "reference": "", "type": "JSON"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "status": {"nullable": "false", "reference": "", "type": "ENUM"},
        "transformation_specification": {"nullable": "false", "reference": "", "type": "JSON"},
        "units": {"nullable": "false", "reference": "", "type": "TEXT"},
        "window_specification": {"nullable": "false", "reference": "", "type": "JSON"},
    },
    "feature_value": {
        "available_to_model_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "computed_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "coverage_definition": {"nullable": "true", "reference": "", "type": "TEXT"},
        "coverage_fraction": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "denominator": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "feature_definition_id": {
            "nullable": "false",
            "reference": "feature_definition.id",
            "type": "HASH",
        },
        "feature_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "feature_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "input_observation_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "missingness_reason": {"nullable": "false", "reference": "", "type": "ENUM"},
        "numerator": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "origin_id": {"nullable": "false", "reference": "research_origin.id", "type": "HASH"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "quality_flags": {"nullable": "false", "reference": "", "type": "JSON"},
        "raw_value_decimal": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "raw_value_text": {"nullable": "true", "reference": "", "type": "TEXT"},
        "raw_value_vector": {"nullable": "true", "reference": "", "type": "TYPED_VECTOR"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "transform_manifest_id": {
            "nullable": "true",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "transform_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "transformed_value": {"nullable": "true", "reference": "", "type": "TYPED_NUMBER"},
        "units": {"nullable": "false", "reference": "", "type": "TEXT"},
        "window_end_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "window_start_at": {"nullable": "false", "reference": "", "type": "UTC"},
    },
    "information_event_version": {
        "available_to_model_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "claim_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "document_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "embedding_version": {"nullable": "true", "reference": "", "type": "TEXT"},
        "entity_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "expectation_available_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "extraction_model_version": {"nullable": "true", "reference": "", "type": "TEXT"},
        "extraction_output": {"nullable": "false", "reference": "", "type": "TYPED_OBJECT"},
        "first_available_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "first_received_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "independent_source_count": {"nullable": "true", "reference": "", "type": "INT64"},
        "lineage_observation_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "market_match_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "match_confidence": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "matching_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "novelty_value": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "numeric_actual_raw": {"nullable": "true", "reference": "", "type": "TEXT"},
        "numeric_expectation_raw": {"nullable": "true", "reference": "", "type": "TEXT"},
        "numeric_unit": {"nullable": "true", "reference": "", "type": "TEXT"},
        "original_source_id": {"nullable": "true", "reference": "", "type": "TEXT"},
        "prompt_hash": {"nullable": "true", "reference": "", "type": "TEXT"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "source_observation_id": {
            "nullable": "false",
            "reference": "source_observation.id",
            "type": "HASH",
        },
        "source_published_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "stance_probabilities": {"nullable": "true", "reference": "", "type": "DECIMAL_VECTOR"},
        "supersedes_id": {
            "nullable": "true",
            "reference": "information_event_version.id",
            "type": "HASH",
        },
        "text_hash": {"nullable": "false", "reference": "", "type": "HASH"},
        "text_hash_scope": {"nullable": "false", "reference": "", "type": "ENUM"},
        "text_rights_state": {"nullable": "false", "reference": "", "type": "ENUM"},
    },
    "label_version": {
        "actual_delay_seconds": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "censoring_reason": {"nullable": "true", "reference": "", "type": "ENUM"},
        "fee_config_version": {"nullable": "true", "reference": "", "type": "TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "label_available_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "label_computation_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "label_id": {"nullable": "false", "reference": "", "type": "HASH"},
        "label_observed_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "label_value": {"nullable": "true", "reference": "", "type": "TYPED_OBJECT"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "origin_id": {"nullable": "false", "reference": "research_origin.id", "type": "HASH"},
        "outcome_observation_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "payout_vector": {"nullable": "true", "reference": "", "type": "DECIMAL_VECTOR"},
        "prediction_id": {"nullable": "true", "reference": "prediction.id", "type": "HASH"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "revision_reason": {"nullable": "true", "reference": "", "type": "TEXT"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "status": {"nullable": "false", "reference": "", "type": "ENUM"},
        "supersedes_label_id": {
            "nullable": "true",
            "reference": "label_version.id",
            "type": "TEXT",
        },
        "target_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "target_definition_id": {
            "nullable": "false",
            "reference": "target_definition.id",
            "type": "HASH",
        },
    },
    "market_identity_version": {
        "category": {"nullable": "true", "reference": "", "type": "TEXT"},
        "close_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "condition_identity_id": {
            "nullable": "true",
            "reference": "condition_identity.id",
            "type": "HASH",
        },
        "event_id": {"nullable": "true", "reference": "", "type": "TEXT"},
        "fee_configuration": {"nullable": "true", "reference": "", "type": "JSON"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "information_event_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "lifecycle_state": {"nullable": "false", "reference": "", "type": "TEXT"},
        "mapping_confidence": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "mapping_evidence_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "mapping_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "market_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "observed_from_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "question": {"nullable": "false", "reference": "", "type": "TEXT"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "resolution_source": {"nullable": "true", "reference": "", "type": "TEXT"},
        "rules_hash": {"nullable": "true", "reference": "", "type": "HASH"},
        "rules_text": {"nullable": "true", "reference": "", "type": "TEXT"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "supersedes_id": {
            "nullable": "true",
            "reference": "market_identity_version.id",
            "type": "HASH",
        },
        "tick_size": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "valid_from_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "valid_to_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "venue": {"nullable": "false", "reference": "", "type": "TEXT"},
    },
    "outcome_observation": {
        "ask": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "available_to_model_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "bid": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "close_state": {"nullable": "false", "reference": "", "type": "TEXT"},
        "executable_size": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "first_received_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "label_observed_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "midpoint": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "missingness_reason": {"nullable": "false", "reference": "", "type": "ENUM"},
        "near_mid_depth": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "observation_status": {"nullable": "false", "reference": "", "type": "ENUM"},
        "origin_id": {"nullable": "false", "reference": "research_origin.id", "type": "HASH"},
        "payout_vector": {"nullable": "true", "reference": "", "type": "DECIMAL_VECTOR"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "resolution_state": {"nullable": "false", "reference": "", "type": "TEXT"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "source_observation_id": {
            "nullable": "false",
            "reference": "source_observation.id",
            "type": "HASH",
        },
        "supersedes_id": {
            "nullable": "true",
            "reference": "outcome_observation.id",
            "type": "HASH",
        },
        "target_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "target_definition_id": {
            "nullable": "false",
            "reference": "target_definition.id",
            "type": "HASH",
        },
        "units": {"nullable": "false", "reference": "", "type": "JSON"},
    },
    "prediction": {
        "abstention_reason": {"nullable": "true", "reference": "", "type": "ENUM"},
        "calibration_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "class_probabilities": {"nullable": "true", "reference": "", "type": "DECIMAL_VECTOR"},
        "direction": {"nullable": "true", "reference": "", "type": "ENUM"},
        "distribution_parameters": {"nullable": "true", "reference": "", "type": "TYPED_OBJECT"},
        "experiment_run_id": {
            "nullable": "false",
            "reference": "experiment_run.id",
            "type": "HASH",
        },
        "feature_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "generated_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "horizon_seconds": {"nullable": "false", "reference": "", "type": "INT64"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "latency_ms": {"nullable": "false", "reference": "", "type": "DECIMAL_TEXT"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "model_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "origin_id": {"nullable": "false", "reference": "research_origin.id", "type": "HASH"},
        "output_kind": {"nullable": "false", "reference": "", "type": "ENUM"},
        "prediction_id": {"nullable": "false", "reference": "", "type": "HASH"},
        "prediction_persisted_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "target_definition_id": {
            "nullable": "false",
            "reference": "target_definition.id",
            "type": "HASH",
        },
        "target_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "training_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "TEXT",
        },
        "uncalibrated_prediction_id": {
            "nullable": "true",
            "reference": "prediction.id",
            "type": "HASH",
        },
    },
    "research_origin": {
        "eligibility_reason": {"nullable": "false", "reference": "", "type": "TEXT"},
        "eligibility_snapshot": {"nullable": "false", "reference": "", "type": "JSON"},
        "eligibility_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "event_group_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "feature_cutoff_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "group_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "legacy_entry_reference": {"nullable": "true", "reference": "", "type": "JSON"},
        "market_identity_id": {
            "nullable": "false",
            "reference": "market_identity_version.id",
            "type": "HASH",
        },
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "origin_id": {"nullable": "false", "reference": "", "type": "HASH"},
        "origin_kind": {"nullable": "false", "reference": "", "type": "ENUM"},
        "origin_recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "prediction_origin_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "sampling_arm": {"nullable": "false", "reference": "", "type": "ENUM"},
        "sampling_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "HASH",
        },
        "scheduled_origin_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "selection_probability": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "token_outcome_id": {
            "nullable": "false",
            "reference": "token_outcome_version.id",
            "type": "HASH",
        },
        "trigger_id": {"nullable": "true", "reference": "", "type": "TEXT"},
    },
    "source_observation": {
        "availability_evidence_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "available_to_model_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "clock_error_bound_ms": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "clock_session_id": {"nullable": "true", "reference": "", "type": "TEXT"},
        "coverage_definition": {"nullable": "true", "reference": "", "type": "TEXT"},
        "coverage_fraction": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "first_available_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "first_received_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "gap_duration_ms": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "ingested_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "legacy_reference": {"nullable": "true", "reference": "", "type": "JSON"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "missing_reason": {"nullable": "false", "reference": "", "type": "ENUM"},
        "native_clock_details": {"nullable": "false", "reference": "", "type": "JSON"},
        "native_record_id": {"nullable": "true", "reference": "", "type": "TEXT"},
        "observation_id": {"nullable": "false", "reference": "", "type": "HASH"},
        "parsed_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "parser_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "payload_encoding": {"nullable": "false", "reference": "", "type": "ENUM"},
        "payload_hash": {"nullable": "false", "reference": "", "type": "HASH"},
        "protocol_version": {"nullable": "true", "reference": "", "type": "TEXT"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "quality_assessment_state": {"nullable": "false", "reference": "", "type": "ENUM"},
        "quality_flags": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "raw_payload_inline": {"nullable": "true", "reference": "", "type": "TEXT"},
        "raw_payload_uri": {"nullable": "true", "reference": "", "type": "TEXT"},
        "raw_timestamp": {"nullable": "true", "reference": "", "type": "TEXT"},
        "receipt_monotonic_ns": {"nullable": "true", "reference": "", "type": "UINT_TEXT"},
        "receipt_ordinal": {"nullable": "false", "reference": "", "type": "INT64"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "request_cursor": {"nullable": "true", "reference": "", "type": "TEXT"},
        "request_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "request_metadata": {"nullable": "false", "reference": "", "type": "JSON"},
        "revision_of": {"nullable": "true", "reference": "source_observation.id", "type": "TEXT"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "source_event_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "source_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "source_published_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "source_registry_id": {
            "nullable": "false",
            "reference": "source_registry.id",
            "type": "HASH",
        },
        "source_sequence": {"nullable": "true", "reference": "", "type": "TEXT"},
        "timestamp_unit": {"nullable": "true", "reference": "", "type": "TEXT"},
    },
    "source_registry": {
        "access_state": {"nullable": "false", "reference": "", "type": "ENUM"},
        "clock_semantics": {"nullable": "false", "reference": "", "type": "JSON"},
        "endpoint": {"nullable": "false", "reference": "", "type": "TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "parser_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "protocol_version": {"nullable": "true", "reference": "", "type": "TEXT"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "registry_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "rights_evidence": {"nullable": "false", "reference": "", "type": "JSON"},
        "rights_state": {"nullable": "false", "reference": "", "type": "ENUM"},
        "schema_hash": {"nullable": "false", "reference": "", "type": "HASH"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "source_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "supersedes_id": {"nullable": "true", "reference": "source_registry.id", "type": "HASH"},
        "unit_conventions": {"nullable": "false", "reference": "", "type": "JSON"},
        "verified_observation_id": {
            "nullable": "true",
            "reference": "source_observation.id",
            "type": "HASH",
        },
    },
    "target_definition": {
        "horizon_seconds": {"nullable": "true", "reference": "", "type": "INT64"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "label_rule": {"nullable": "false", "reference": "", "type": "JSON"},
        "metric_contract": {"nullable": "false", "reference": "", "type": "JSON"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "quote_rule": {"nullable": "false", "reference": "", "type": "JSON"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "target_family": {"nullable": "false", "reference": "", "type": "ENUM"},
        "target_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "units": {"nullable": "false", "reference": "", "type": "TEXT"},
    },
    "token_outcome_version": {
        "chain_id": {"nullable": "true", "reference": "", "type": "INT64"},
        "condition_identity_id": {
            "nullable": "true",
            "reference": "condition_identity.id",
            "type": "HASH",
        },
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "mapping_evidence_ids": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "mapping_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "market_identity_id": {
            "nullable": "false",
            "reference": "market_identity_version.id",
            "type": "HASH",
        },
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "observed_from_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "outcome_index": {"nullable": "true", "reference": "", "type": "INT64"},
        "outcome_label": {"nullable": "true", "reference": "", "type": "TEXT"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "supersedes_id": {
            "nullable": "true",
            "reference": "token_outcome_version.id",
            "type": "HASH",
        },
        "token_contract": {"nullable": "true", "reference": "", "type": "ADDRESS"},
        "token_id": {"nullable": "true", "reference": "", "type": "UINT_TEXT"},
        "valid_from_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "valid_to_at": {"nullable": "true", "reference": "", "type": "UTC"},
    },
    "trade_observation": {
        "aggressor_side": {"nullable": "true", "reference": "", "type": "ENUM"},
        "block_hash": {"nullable": "true", "reference": "", "type": "HEX32"},
        "block_number": {"nullable": "true", "reference": "", "type": "UINT_TEXT"},
        "chain_id": {"nullable": "true", "reference": "", "type": "INT64"},
        "deduplication_status": {"nullable": "false", "reference": "", "type": "ENUM"},
        "deduplication_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "economic_fill_key": {"nullable": "true", "reference": "", "type": "TEXT"},
        "fee_native": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "fee_unit": {"nullable": "true", "reference": "", "type": "TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "log_index": {"nullable": "true", "reference": "", "type": "INT64"},
        "maker_wallet": {"nullable": "true", "reference": "", "type": "TEXT"},
        "match_status": {"nullable": "false", "reference": "", "type": "ENUM"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "notional_currency": {"nullable": "false", "reference": "", "type": "TEXT"},
        "price_decimal": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "settlement_status": {"nullable": "false", "reference": "", "type": "ENUM"},
        "side_semantics_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "size_decimal": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "source_observation_id": {
            "nullable": "false",
            "reference": "source_observation.id",
            "type": "HASH",
        },
        "supersedes_id": {"nullable": "true", "reference": "trade_observation.id", "type": "HASH"},
        "taker_wallet": {"nullable": "true", "reference": "", "type": "TEXT"},
        "token_outcome_id": {
            "nullable": "false",
            "reference": "token_outcome_version.id",
            "type": "HASH",
        },
        "trade_id": {"nullable": "false", "reference": "", "type": "TEXT"},
        "trade_notional": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "trade_price_raw": {"nullable": "false", "reference": "", "type": "TEXT"},
        "trade_size_raw": {"nullable": "false", "reference": "", "type": "TEXT"},
        "transaction_hash": {"nullable": "true", "reference": "", "type": "HEX32"},
    },
    "wallet_state_version": {
        "as_of_cutoff_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "attribution_confidence": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "available_to_model_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "chain_id": {"nullable": "false", "reference": "", "type": "INT64"},
        "coverage_start_at": {"nullable": "true", "reference": "", "type": "UTC"},
        "first_observed_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "history_coverage_fraction": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "history_manifest_id": {
            "nullable": "false",
            "reference": "artifact_manifest.id",
            "type": "TEXT",
        },
        "holding_shares": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "id": {"nullable": "false", "reference": "", "type": "HASH"},
        "missing_fields": {"nullable": "false", "reference": "", "type": "JSON"},
        "net_flow": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "prior_mature_event_count": {"nullable": "false", "reference": "", "type": "INT64"},
        "provenance_class": {"nullable": "false", "reference": "", "type": "ENUM"},
        "recorded_at": {"nullable": "false", "reference": "", "type": "UTC"},
        "role_flags": {"nullable": "false", "reference": "", "type": "ID_LIST"},
        "schema_version": {"nullable": "false", "reference": "", "type": "TEXT"},
        "skill_posterior_mean": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "skill_posterior_sd": {"nullable": "true", "reference": "", "type": "DECIMAL_TEXT"},
        "state_definition_version": {"nullable": "false", "reference": "", "type": "HASH"},
        "supersedes_id": {
            "nullable": "true",
            "reference": "wallet_state_version.id",
            "type": "HASH",
        },
        "token_outcome_id": {
            "nullable": "true",
            "reference": "token_outcome_version.id",
            "type": "HASH",
        },
        "uncertainty": {"nullable": "false", "reference": "", "type": "JSON"},
        "wallet_id": {"nullable": "false", "reference": "", "type": "TEXT"},
    },
}
